### ISSUE TITLE
Support for Angular 14 and later 

### ISSUE THREAD

**Issue by AmrBouaziz** [enten/ngx-sticky#37]
Technically the library can support angular version up to 14 but the peerDependencies declare 
<pre>
    "@angular/common": "^12.2.0",
    "@angular/core": "^12.2.0",
</pre>

running the command `npm update --save` will throw errors as the dependency resolver will faill to meet the required angular 12 peer dependency.

Will this be an acceptable compromise 
<pre>
    "@angular/common": ">=12.2.0",
    "@angular/core": ">=12.2.0",
</pre>

**Comment by enten** [comment]
Closed by the releasing distinct versions for backward support from angular 6 to 16.

## Showcases

| @enten/ngx-sticky | @angular/core | rxjs |
|-|-|-|
| [`16.0.0`](https://enten.github.io/ngx-sticky/v/16.0.0) | `^16.0.0` | `^6.5.3 \|\| ^7.4.0` |
| [`15.0.0`](https://enten.github.io/ngx-sticky/v/15.0.0) | `^15.0.0` | `^6.5.3 \|\| ^7.4.0` |
| [`14.0.0`](https://enten.github.io/ngx-sticky/v/14.0.0) | `^14.0.0` | `^6.5.3 \|\| ^7.4.0` |
| [`13.0.0`](https://enten.github.io/ngx-sticky/v/13.0.0) | `^13.0.0` | `^6.5.3 \|\| ^7.4.0` |
| [`12.0.0`](https://enten.github.io/ngx-sticky/v/12.0.0) | `^12.0.0` | `^6.5.3 \|\| ^7.0.0` |
| [`11.0.0`](https://enten.github.io/ngx-sticky/v/11.0.0) | `^11.0.0` | `^6.5.3` |
| [`10.0.0`](https://enten.github.io/ngx-sticky/v/10.0.0) | `^10.0.0` | `^6.5.3` |
| [`9.0.0`](https://enten.github.io/ngx-sticky/v/9.0.0) | `^9.0.0` | `^6.5.3` |
| [`8.0.0`](https://enten.github.io/ngx-sticky/v/8.0.0) | `^8.0.0` | `^6.4.0` |
| [`7.0.0`](https://enten.github.io/ngx-sticky/v/7.0.0) | `^7.0.0` | `>=6.0.0 <6.4.0` |
| [`6.0.0`](https://enten.github.io/ngx-sticky/v/6.0.0) | `^6.0.0` | `>=6.0.0 <6.4.0` |
