### ISSUE TITLE
Could you update all related Angular libs to version 17?

### ISSUE THREAD

**Issue by tony-chen-rci** [enten/ngx-sticky#53]
Thanks.

**Comment by enten** [comment]
@tony-chen-rci 
Check [@enten/ngx-sticky@17.0.0](https://www.npmjs.com/package/@enten/ngx-sticky/v/17.0.0) ([showcase](https://enten.github.io/ngx-sticky/v/17.0.0)).

**Comment by tony-chen-rci** [comment]
thanks.
